language: node_js
node_js:
- node
- lts/*
- '10'
- '9'
- '8'
- '7'
- '6'
- '5'
- '4'
cache: yarn
after_success: yarn coverage
deploy:
  on:
    node: node
    branch: npm
  provider: npm
  email: bram@bram.codes
  api_key:
    secure: cdQt9GqLo9OBo25WtP03FwbAo575hElm9FAO7v417wn9uV2kNjhENR2svC/qormju0uhZntjDhysOve92Ib5TenbAPW6Fg+H6WsxP5VVSa6lvwnSUVtki+hV6ltn5kk1TuRbppe2B3ysqN/F869DHgDH/WODi7gfr5eiuw/XOAjsoAs352hdqlbS0CUOqDJ1dL5ByhMFxIPNtVXQ10cGj56fZVifqhIfndPnxRFqL9ZaT6aIMEUQ66No9oOer5SrUGJPYkUKGKPBp1UpqYAq4N3JX+2zveI8sPtzLblQJVEaHKpPtvfSpatoNruLt8LdVryOINBQHwoQ/X85ugLqudy95gEWVftbT6lL500PYCdMLrFIfaNKNOPXWnFWau23j2RdepQIQa01OCBxEUW9yIGhdt9XiC9uMsAJVJivnEkoi/8PMHJqNIG3yoctnBCOhA0JiT8ojWoBJhXzRXPPMxv+4jVlZHkcRmydTVuZnzGNnm7wDEwO/Ny4bePwiyrYoYHtkJ31r4c9YiLb1sik3m0C9/K2mThpOYvJhjUIbNW1m4TUic3Nn4i5fgLNfymzSj2SBnRPyEk5L4pPsW3KqS6zj5rx2tY4G3VqTJnBqhZW1f3E0oROh0ljGmMZVHHK+Yi6qUa3Q8uvH2q8ZSL51G+8P040Ct1ViA0O4FQfpHk=
