language: node_js
node_js:
- node
- lts/*
- '10'
- '9'
- '8'
- '7'
- '6'
- '5'
- '4'
cache: yarn
after_success: yarn coverage
deploy:
  on:
    node: node
    branch: npm
  provider: npm
  email: bram@bram.codes
  api_key:
    secure: LFxml0776ipQn7hzHS0fpXAh/Rlcsv6u8bDAvtmeJwu6XeDlQoBnO1nZgCvrblcHm/719odlDdE3HW3bMIt/06HiCPaGr8dT7QykODYD/BUAmhyDAI8H+zY4eYYEiqW6aj54VpNxq8D/RJPv2dct1TynGhU4I00qfiCO3DyG/b/rfrJOG91PfJP0FrakyC1HKpt2r8dZBjdy/rFgcibf1zaaS3QNSK1WCd1w9P9oRrcBANKw1tZX+rNECHAWw1/d+EFhJ/pz+d7zL4RRcAUeu9LTooTjK75INrrKQLbLFzP0uqbonxjqc/coBKaUqHHvC4EBPTPpMxgYx1J8klzKfm93ygmK4+A9YnUalCh9TOjDy1d+XPl5SHwCDZTr7SwMGae80vo3tEGQoSNQXXyGcWrJ1K1moHTeA/ZVNW56RNRvyO5wJf3PsI9K7Pk4dMCWdYEN/ZwfHYplLwcwInn1DEw7ieKJz7DBNYrMOAGd0Z65vFaMYEV3ZFlZwA7GS3DiUy3WX6b52OsA++QlcLHUoPbvST8FIf76NOPKaXiw6nm/0guisnd/EUHQl1RI2m2P11YM56Jp2HyRWgqYvo6wsUlew+yZ20TKrhuZM+ijD5XiHa1YHHQpcQR17ejE1evPqrR7MVHWgbq3EfkO5JRMR05N6lR5SbSOhNJitLMK97g=
