language: node_js
node_js:
  - "node"
  - "lts/*"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
cache: yarn
after_success: yarn coverage
deploy:
  on:
    node: '10.0.0'
    branch: npm
  provider: npm
  email: bram@bram.codes
  api_key:
    secure: QnZzbQEOqAhpiHyMEdnrbfClVw37gsIo75J3uAdGC+ICHCR4RV0gume/tlOBw26yEu0m7YVA3dmYJfg48wHAVk+ZEsE6fQ2AD2fjIEgStqyELfkUWICJ1Zatk8xZXWuzKx8fOJx4Zzazwv8bwKFwqqPwkbPM+EFlDf+IgyKpzldlHhJvI2j6N3y4RiBMauPw3RLgwfDD8Y41LzjCJ4eTKbCyRKMxsr0EHUfpVQz6i5h5rF5sUcp8O2ugAVdjCfpI13poycvRlAjPaXI3tla4x553delPUd2KtQJli1/iThdYObuJl/OZFiuCFfDxL4oBEj9cf5dk+H1Hv4vfOsImYh8uQL6L78lN6azPgCQslG6bSXDy0nQMrIko79xwRIhmZalpg9Y/0HxL5+MIlmSEOL+a/W8D2dO27c22cJ71LxA6leeSpeaVxnJgbNOLnVXP49EZ/k7AMtE2mC+P541XhS2ZJNJF2G1oe6UV7ouhYZjfxuIi3CewRQrjJdhCQoXyB2ZT5ORmDT08tU3/Ay0VeWc5aP6+DLxdcJUnvCQwwQxhEXA0ElHPOphkb4wbt1RTlRdjml61zu0sMZ28t9x0j/C/y6UTA7ybu4894J5MPYZSIr02iS6ystKPOlJj/Z/AAFZ1i/Tlc6SKeaB8YlcUB34tPEAHOYPN4REgA1HICYY=
