language: node_js
node_js:
- node
- lts/*
- '10'
- '9'
- '8'
- '7'
- '6'
- '5'
- '4'
cache: yarn
after_success: yarn coverage
deploy:
  on:
    node: node
    branch: npm
  provider: npm
  email: bram@bram.codes
  api_key: $NPM_TOKEN
